### ISSUE TITLE
GoModExtractor test cases failing

### ISSUE THREAD

**Issue by jakeryang** [depscloud/depscloud#101]
While I was working on #98 I noticed that the test cases for GoModExtractor were failing.

The ending parentheses were not being parsed properly and the for-loop were checking for `)` rather than `)\r`.

Will open a PR to fix this.

**Comment by mjpitz** [comment]
Ah, you're on a windows machine. That could explain it.

**Comment by mjpitz** [comment]
I don't have an editor config setup for the repo. Probably worth putting one together at some point.

**Comment by jakeryang** [comment]
Can you add `hacktoberfest` tag?

**Comment by mjpitz** [comment]
Because this project is not just under the general Hacktoberfest event but also the Indeed one, there are some things I need to be careful of with regard to the hacktoberfest label (specifically issue sizing). I'd say the combination of this and gh-69 (gh-98) is better scoped for Indeed is looking for. Otherwise I would've.
